apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          args: ["--auth","--dbpath","/data/db"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          livenessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --disableImplicitSessions
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          ports:
            - containerPort: 27017
              name: mongo-port
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
          volumeMounts:
          - name: "mongo-data-dir"
            mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "mongodb-claim" # claimName from PersistentVolumeClaim
      restartPolicy: Always
      runAsNonRoot: true
      runAsUser: 999
---
kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: mongo-port
  selector:
    app: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-claim
  namespace: vp-registry
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: csi-cinder-high-speed # change to storageClassName
---
apiVersion: v1
data:
  password: cGFzc3dvcmQxMjM= #password123 use correct password here
  username: YWRtaW51c2Vy     #adminuser change to corrrect user
kind: Secret
metadata:
  name: mongo-creds
  namespace: vp-registry
